/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.util.Vector;

/**
 *
 * @author andres
 */
public class PanelBtnEmpleadoCre extends javax.swing.JPanel {

    private JFramePrincipal JFrame;
    private Vector<String> typeEmpleados = new Vector<String>();
    /**
     * Creates new form PanelBtnEmpleadoCre
     */
    public PanelBtnEmpleadoCre(JFramePrincipal JFrame) {
        initComponents();
        this.JFrame = JFrame;
        this.setSize(600, 200);
        this.setBackground(new Color(43, 140, 196));
        setTextOfInfoLabel("");
        typeEmpleados.add("Programador");
        typeEmpleados.add("Analista");
        setUpFilter();
        setUpPanelTypeEmple();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        jcombTypeEmple = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblInfo.setText("jLabel1");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jcombTypeEmple.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcombTypeEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombTypeEmpleActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de empleado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcombTypeEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(184, 184, 184)
                        .addComponent(lblInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(btnCrear)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcombTypeEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(btnCrear)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(lblInfo))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame.swapBotonPanelBtnInicio();
        JFrame.swapContentPanelInicio();
        setTextOfInfoLabel("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        JFrame.getDataFromBoxes();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void jcombTypeEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombTypeEmpleActionPerformed
        setUpPanelTypeEmple();
    }//GEN-LAST:event_jcombTypeEmpleActionPerformed

    
    public void setUpPanelTypeEmple(){
        JFrame.putFilterEmpleadoPanel(getTypeEmple());
    }
    
    // uso boolean por que solo hay dos tipos, pero obv si hubiera mas pasario un valor cada uno significando un tipo de Empleado
    public boolean getTypeEmple(){
        int tipoEmple = jcombTypeEmple.getSelectedIndex();
        
        if(tipoEmple>=0){
            if(typeEmpleados.get(tipoEmple).equals("Analista")){
                return false;
            }
        }
        // por defecto sera programador
        return true;
    }

    public void setUpFilter(){
        jcombTypeEmple.removeAllItems();
        for(String part: typeEmpleados){
            jcombTypeEmple.addItem(part);
        }
    }
    
    public void setTextOfInfoLabel(String info){
        lblInfo.setText(info);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jcombTypeEmple;
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables
}
