/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.MyList;
import Modelo.Empleado;
import java.awt.*;
import java.util.List;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author andres
 */
public class PanelBtnInicio extends javax.swing.JPanel {

    
    private JFramePrincipal JFrame;
    private MyList listaEmpleadosEnPanel;
    /**
     * Creates new form PanelBtnInicio
     */
    public PanelBtnInicio(JFramePrincipal JFrame) {
        initComponents();
        this.JFrame = JFrame;
        this.setSize(600, 200);
        this.setBackground(new Color(43, 140, 196));
        System.out.println("B) La lista esta vacia?"+JFrame.getListaEmpleados().isEmpty());
        modifyLabelListaState();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        lblInfoListaState = new javax.swing.JLabel();

        btn1.setText("Cargar Fichero");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn4.setText("Visualizar");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn2.setText("Guardar Fichero");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("Crear");

        lblInfoListaState.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfoListaState)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn4)
                    .addComponent(btn2)
                    .addComponent(btn3))
                .addGap(55, 55, 55)
                .addComponent(lblInfoListaState)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // boton visualizar
    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        JFrame.swapBotonPanelVisuMenu();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            // va a ser null si cancelamos o cerramos la ventana
            System.out.println(filename);
            
            MyList nuevaLista = new MyList();
            List<Empleado> lista = nuevaLista.deserialization(filename);
            for(int i=0;i<lista.size();i++){
                nuevaLista.add(lista.get(i));
                nuevaLista.getPointerLast().setIndice(lista.get(i).getNumero()-1);
            }
            System.out.println("LISTA DESEARIALIZADA:");
            nuevaLista.showMyList();
        }catch (NullPointerException npe){
            System.out.println("No se ha seleccionado un fichero");
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        JFrame.swapBotonPanelGuardarFichero();
    }//GEN-LAST:event_btn2ActionPerformed

    public void modifyLabelListaState(){
        //String state = (!JFrame.getListaEmpleados().isEmpty())?"Hay empleados cargados":"No hay empleados en la lista";
        String state;
        if(JFrame.getListaEmpleados().isEmpty()){
            state = "No hay empleados en la lista";
            btn2.setEnabled(false);
        }else{
            state = "Hay empleados cargados";
            btn2.setEnabled(true);
        }
        lblInfoListaState.setText(state);
        JFrame.getListaEmpleados().showMyList();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JLabel lblInfoListaState;
    // End of variables declaration//GEN-END:variables
}
