/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.MyList;
import Modelo.Analista;
import Modelo.Empleado;
import Modelo.Programador;
import java.awt.BorderLayout;
import java.awt.Color;
import static java.util.Calendar.DAY_OF_MONTH;
import static java.util.Calendar.MONTH;
import static java.util.Calendar.YEAR;

/**
 *
 * @author andres
 */
public class PanelContentEmpleadoVis extends javax.swing.JPanel {

    private JFramePrincipal JFrame;
    
    /**
     * Creates new form PanelContentVisualizar
     */
    public PanelContentEmpleadoVis(JFramePrincipal JFrame) {
        initComponents();
        this.JFrame = JFrame;
        this.setSize(600, 350);
        this.setBackground(Color.green);
        fillBoxes(JFrame.getListaEmpleados());
        setBoxesEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txBxNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txBxNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txBxApellido = new javax.swing.JTextField();
        txBxSaldo = new javax.swing.JTextField();
        txBxSaldoMax = new javax.swing.JTextField();
        txBxFechaAlta = new javax.swing.JTextField();
        PanelTipoEmpleado = new javax.swing.JPanel();

        txBxNumero.setText("jTextField1");

        jLabel1.setText("Número:");

        jLabel2.setText("Nombre:");

        txBxNombre.setText("jTextField2");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Saldo:");

        jLabel5.setText("SaldoMax:");

        jLabel6.setText("Fecha Alta:");

        txBxApellido.setText("jTextField3");

        txBxSaldo.setText("jTextField4");

        txBxSaldoMax.setText("jTextField5");

        txBxFechaAlta.setText("jTextField6");

        PanelTipoEmpleado.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout PanelTipoEmpleadoLayout = new javax.swing.GroupLayout(PanelTipoEmpleado);
        PanelTipoEmpleado.setLayout(PanelTipoEmpleadoLayout);
        PanelTipoEmpleadoLayout.setHorizontalGroup(
            PanelTipoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );
        PanelTipoEmpleadoLayout.setVerticalGroup(
            PanelTipoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txBxFechaAlta)
                    .addComponent(txBxSaldoMax)
                    .addComponent(txBxSaldo)
                    .addComponent(txBxApellido)
                    .addComponent(txBxNombre)
                    .addComponent(txBxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(PanelTipoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txBxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txBxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txBxApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txBxSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txBxSaldoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txBxFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void swapContentPanelEmpleadoVisPro(Programador pro){
        PanelContentEmpleadoVisPro PanelPro = new PanelContentEmpleadoVisPro(JFrame);
        PanelPro.fillBoxes(pro);
        PanelTipoEmpleado.removeAll();
        PanelTipoEmpleado.add(PanelPro, BorderLayout.CENTER);
        PanelTipoEmpleado.revalidate();
        PanelTipoEmpleado.repaint();
    }
    
    public void swapContentPanelEmpleadoVisAna(Analista ana){
        PanelContentEmpleadoVisAna PanelAna = new PanelContentEmpleadoVisAna(JFrame);
        PanelAna.fillBoxes(ana);
        PanelTipoEmpleado.removeAll();
        PanelTipoEmpleado.add(PanelAna, BorderLayout.CENTER);
        PanelTipoEmpleado.revalidate();
        PanelTipoEmpleado.repaint();
    }
    
    public void fillBoxes(MyList lista){
        if(!lista.isEmpty()){
            Empleado aux = (Empleado)lista.getPointerActual().getMain();
            txBxApellido.setText(""+aux.getApellido());
            //txFechaAlta.setText(""+(aux.getFechaAlta()).toInstant());
            txBxFechaAlta.setText(""+(aux.getFechaAlta()).get(DAY_OF_MONTH)
                +"/"+(aux.getFechaAlta()).get(MONTH)
                +"/"+(aux.getFechaAlta()).get(YEAR));
            txBxNombre.setText(""+aux.getNombre());
            txBxNumero.setText(""+aux.getNumero());
            txBxSaldo.setText(""+aux.getSaldo());
            txBxSaldoMax.setText(""+aux.getSaldoMax());
        }else{
            emptyBoxes();
        }
    }
    
    public void emptyBoxes(){
        txBxApellido.setText("");
        txBxFechaAlta.setText("");
        txBxNombre.setText("");
        txBxNumero.setText("");
        txBxSaldo.setText("");
        txBxSaldoMax.setText("");
    }
    
    public void setBoxesEditable(boolean typeOfEditable){
        txBxApellido.setEditable(typeOfEditable);
        txBxFechaAlta.setEditable(typeOfEditable);
        txBxNombre.setEditable(typeOfEditable);
        txBxNumero.setEditable(typeOfEditable);
        txBxSaldo.setEditable(typeOfEditable);
        txBxSaldoMax.setEditable(typeOfEditable);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTipoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txBxApellido;
    private javax.swing.JTextField txBxFechaAlta;
    private javax.swing.JTextField txBxNombre;
    private javax.swing.JTextField txBxNumero;
    private javax.swing.JTextField txBxSaldo;
    private javax.swing.JTextField txBxSaldoMax;
    // End of variables declaration//GEN-END:variables
}
