/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.MyList;
import Modelo.Empleado;
import java.awt.Color;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author andres
 */
public class PanelBtnCargarFichero extends javax.swing.JPanel {

    private JFramePrincipal JFrame;
    /**
     * Creates new form PanelBtnCargarFichero
     */
    public PanelBtnCargarFichero(JFramePrincipal JFrame) {
        initComponents();
        this.JFrame = JFrame;
        this.setSize(600, 200);
        this.setBackground(new Color(255, 162, 55));
        lblInfo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAddIntoList = new javax.swing.JButton();
        btnSobreescribirList = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("¿Cómo quiere cargar el fichero?");

        btnAddIntoList.setText("Añadir contenido al existente");
        btnAddIntoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIntoListActionPerformed(evt);
            }
        });

        btnSobreescribirList.setText("Sobreescribir contenido");
        btnSobreescribirList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreescribirListActionPerformed(evt);
            }
        });

        lblInfo.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnAddIntoList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnSobreescribirList)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(lblInfo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddIntoList)
                    .addComponent(btnSobreescribirList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblInfo)
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame.swapBotonPanelBtnInicio();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSobreescribirListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreescribirListActionPerformed
        accionDeGuardar(false);
    }//GEN-LAST:event_btnSobreescribirListActionPerformed

    private void btnAddIntoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIntoListActionPerformed
        accionDeGuardar(true);
    }//GEN-LAST:event_btnAddIntoListActionPerformed

    // tipoAccion? añade:sobreescribe
    public void accionDeGuardar(boolean tipoAccion){
        String mens = (tipoAccion)? "¿Desea añadir a la lista existente?":"¿Desea sobreescribir la lista existente? Perderá todo su contenido";
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, mens,"Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            try{
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            // va a ser null si cancelamos o cerramos la ventana
            System.out.println(filename);
            
            
            MyList nuevaLista = new MyList();
            List<Empleado> lista = nuevaLista.deserialization(filename);
            for(int i=0;i<lista.size();i++){
                nuevaLista.add(lista.get(i));
                nuevaLista.getPointerLast().setIndice(lista.get(i).getNumero()-1);
            }
            
            if(tipoAccion){
                JFrame.addFromFileToList(nuevaLista);
                lblInfo.setForeground(Color.black);
                lblInfo.setText("Se han añadido datos a la lista");
            }
            else if(!tipoAccion){
                JFrame.overWriteFileToList(nuevaLista);
                lblInfo.setForeground(Color.black);
                lblInfo.setText("Se han sobreescrito los datos de la lista");
            }
            
            
            }catch (NullPointerException npe){
                System.out.println("No se ha seleccionado un fichero");
                lblInfo.setForeground(Color.red);
                lblInfo.setText("No se ha seleccionado un fichero");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddIntoList;
    private javax.swing.JButton btnSobreescribirList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables
}
