/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.MyList;
import Modelo.Empleado;

/**
 *
 * @author alumno
 */
public class VistaMenu extends javax.swing.JFrame {

    private MyList listaEmpleados;
    
    boolean createState = false;
    boolean modifyState = false;
    
    boolean btnSigState;
    boolean btnAntState;
    
    public VistaMenu() {
        initComponents();
        btnAnterior.setEnabled(false);
        
        // creamos nuestar lista de empleados
        listaEmpleados = new MyList();
        
        // insertamos empleados
        for(int i=0;i<5;i++){
            Empleado e = new Empleado(i+1);
            listaEmpleados.add(e);
        }
        fillBoxes(listaEmpleados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        txApellido = new javax.swing.JTextField();
        txSaldo = new javax.swing.JTextField();
        txNumero = new javax.swing.JTextField();
        txFechaAlta = new javax.swing.JTextField();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Saldo:");

        jLabel5.setText("Fecha alta:");

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAnterior)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(txApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txFechaAlta)
                                    .addComponent(txSaldo)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSiguiente))))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrar)
                        .addGap(12, 12, 12)
                        .addComponent(btnModificar)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnBorrar)
                    .addComponent(btnModificar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        if(!listaEmpleados.isLast()){
            btnAnterior.setEnabled(true);
            btnSiguiente.setEnabled(true);
            listaEmpleados.getNext();
            fillBoxes(listaEmpleados);
            if(listaEmpleados.isLast())
                btnSiguiente.setEnabled(false);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        
        if(!listaEmpleados.isFirst()){
            btnSiguiente.setEnabled(true);
            btnAnterior.setEnabled(true);
            listaEmpleados.getPrevious();
            fillBoxes(listaEmpleados);
            if(listaEmpleados.isFirst())
                btnAnterior.setEnabled(false);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        if(createState == false){
            emptyBoxes();
            createState = true;
            txFechaAlta.setText("Campo automatico");
            btnSigState = btnSiguiente.isEnabled();
            btnAntState = btnAnterior.isEnabled();
            btnSiguiente.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnModificar.setEnabled(false);
            btnBorrar.setText("Cancelar");
        }else{
            if(txNumero.getText().isEmpty()){
                txNumero.setText("Campo obligatorio");
            }
            else{
                Empleado newEmpleado = getInfoFromCurrentBoxes();
                listaEmpleados.add(newEmpleado);
                
                if(listaEmpleados.getCont()<=0)
                    btnSiguiente.setEnabled(btnSigState);
                else
                    btnSiguiente.setEnabled(true);
                btnAnterior.setEnabled(btnAntState);
                btnModificar.setEnabled(true);
                btnBorrar.setText("Borrar");
                createState = false;
                
                fillBoxes(listaEmpleados);
            }
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        if(createState == false){
            System.out.println(listaEmpleados.getCurrentNode().getMain());
            listaEmpleados.remove(listaEmpleados.getCurrentNode().getMain());
            fillBoxes(listaEmpleados);
            System.out.println("EMPLEADO BORRADO");
            listaEmpleados.showMyList();
        }else{
            // esta parte de boton borrar forma parte del boton cancelar de crear
            if(listaEmpleados.getCont()<=0)
                    btnSiguiente.setEnabled(btnSigState);
                else
                    btnSiguiente.setEnabled(true);
            btnAnterior.setEnabled(btnAntState);
            btnModificar.setEnabled(true);
            btnBorrar.setText("Borrar");
            createState = false;
            
            fillBoxes(listaEmpleados);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(modifyState == false){
            modifyState = true;
            txFechaAlta.setText("Campo automatico");
            btnSigState = btnSiguiente.isEnabled();
            btnAntState = btnAnterior.isEnabled();
            btnSiguiente.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnCrear.setEnabled(false);
            btnBorrar.setText("Cancelar");
        }else{
            Empleado modifiedEmpleado = getInfoFromCurrentBoxes();
            listaEmpleados.modify(listaEmpleados.getCurrentNode().getMain(), modifiedEmpleado);
            
            if(listaEmpleados.getCont()<=0)
                btnSiguiente.setEnabled(btnSigState);
            else
                btnSiguiente.setEnabled(true);
            btnAnterior.setEnabled(btnAntState);
            btnCrear.setEnabled(true);
            btnBorrar.setText("Borrar");
            modifyState = false;
            
            fillBoxes(listaEmpleados);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }
    
    public void fillBoxes(MyList lista){
        Empleado aux = (Empleado)lista.getPointerActual().getMain();
        txApellido.setText(""+aux.getApellido());
        txFechaAlta.setText(""+(aux.getFechaAlta()).toInstant());
        txNombre.setText(""+aux.getNombre());
        txNumero.setText(""+aux.getNumero());
        txSaldo.setText(""+aux.getSaldo());
    }
    
    public void emptyBoxes(){
        txApellido.setText("");
        txFechaAlta.setText("");
        txNombre.setText("");
        txNumero.setText("");
        txSaldo.setText("");
    }
    
    public Empleado getInfoFromCurrentBoxes(){
        int numero;
        String nombre;
        String apellido;
        double saldo;

        if(txNombre.getText().isEmpty())
            nombre = null;
        else
            nombre = txNombre.getText();
        if(txApellido.getText().isEmpty())
            apellido = null;
        else
            apellido = txApellido.getText();
        try{
            numero = Integer.parseInt(txNumero.getText());
        }catch(NumberFormatException e){
            System.out.println("El valor no es un número válido.");
            numero = 0;
        }
        try{
            saldo = Double.parseDouble(txSaldo.getText());
        }catch(NumberFormatException e){
            System.out.println("El valor no es un número válido.");
            saldo = 0;
        }
        Empleado newEmpleado = new Empleado(numero,nombre,apellido,saldo);
        return newEmpleado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txApellido;
    private javax.swing.JTextField txFechaAlta;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txNumero;
    private javax.swing.JTextField txSaldo;
    // End of variables declaration//GEN-END:variables
}
